# Generated by Django 3.0.3 on 2020-02-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('child3_column', models.CharField(max_length=255)),
                ('comments3', models.CharField(max_length=255, null=True)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraviews_test.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('child2_column', models.CharField(max_length=255)),
                ('comments2', models.CharField(max_length=255, null=True)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraviews_test.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('child1_column', models.CharField(max_length=255)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraviews_test.Parent')),
            ],
        ),
    ]
