# Generated by Django 3.0.3 on 2020-02-11 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kakeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoto', models.CharField(max_length=100)),
                ('money', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('Kakeibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Kakeibo')),
            ],
        ),
    ]
