# Generated by Django 3.0.3 on 2020-02-16 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kakeibo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=50, unique=True, verbose_name='支払者')),
            ],
            options={
                'verbose_name': '支払者',
                'verbose_name_plural': '支払者',
                'db_table': 'payer',
            },
        ),
        migrations.CreateModel(
            name='Kakeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('money', models.IntegerField(help_text='単位は円', verbose_name='金額')),
                ('memo', models.CharField(default=' ', max_length=500, verbose_name='メモ')),
                ('seisan', models.BooleanField(default=False, verbose_name='清算')),
                ('category', models.ForeignKey(default=kakeibo.models.get_or_create_default_category, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.Category', verbose_name='カテゴリ')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.Payer', verbose_name='支払者')),
            ],
            options={
                'verbose_name': '家計簿',
                'verbose_name_plural': '家計簿',
                'db_table': 'kakeibo',
            },
        ),
    ]
