# Generated by Django 3.0.3 on 2020-02-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='memo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='メモ'),
        ),
    ]
