# Generated by Django 3.0.3 on 2020-02-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Kakeibo',
            new_name='kakeibo',
        ),
    ]
