# Generated by Django 3.0.3 on 2020-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_auto_20200216_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakeibo',
            name='seisan',
            field=models.BooleanField(default=False, verbose_name='清算'),
        ),
    ]
