# Generated by Django 3.0.3 on 2020-02-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_auto_20200217_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakeibo',
            name='seisan_ymd',
            field=models.DateField(blank=True, null=True, verbose_name='清算日'),
        ),
    ]
