# Generated by Django 3.0.3 on 2020-02-16 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_kakeibo_seisan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=50, unique=True, verbose_name='支払者')),
            ],
            options={
                'verbose_name': '支払者',
                'verbose_name_plural': '支払者',
                'db_table': 'payer',
            },
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.Payer', verbose_name='支払者'),
        ),
    ]
