# Generated by Django 3.0.3 on 2020-02-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_auto_20200213_2243'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kakeibo',
            table='kakeibo',
        ),
    ]
