# Generated by Django 3.0.3 on 2020-02-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_auto_20200216_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.Category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='memo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.Payer', verbose_name='支払者'),
        ),
    ]
