# Generated by Django 3.0.3 on 2020-02-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_auto_20200213_2326'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expense',
        ),
    ]
