# Generated by Django 3.0.3 on 2020-02-16 12:47

from django.db import migrations, models
import django.db.models.deletion
import kakeibo.models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0007_auto_20200216_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='category',
            field=models.ForeignKey(default=kakeibo.models.get_or_create_default_category, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.Category', verbose_name='カテゴリ'),
        ),
    ]
